package schemas.alunoIa

/**
 * Currículo de francês da Missão Fluência — mesma estrutura e progressão pedagógica do
 * [MissionFluencyCurriculum] (inglês), adaptada à gramática do francês. Conteúdo gerado
 * como primeira versão: revisar com um falante nativo antes de publicar para alunos.
 */
private val francesModule1: List<MissionDay> = listOf(
    MissionDay(1, "Articles définis et indéfinis (le/la/les, un/une/des)",
        "Ask about the things on the student's desk, in their bag or around their room right now."),
    MissionDay(2, "Adjectifs possessifs (mon, ton, son, notre...)",
        "Talk about family members — their jobs, their habits, their things ('la voiture de mon frère', 'son travail')."),
    MissionDay(3, "Présent progressif (être en train de + infinitif)",
        "Ask what's happening right now around the student, or what people in their house are doing at this moment."),
    MissionDay(4, "Présent (verbes réguliers et irréguliers)",
        "Talk about the student's daily routine — what they usually do on a normal weekday."),
    MissionDay(5, "Dire l'heure",
        "Ask about the student's schedule today — what time they woke up, have lunch, or need to leave for something."),
    MissionDay(6, "Adverbes de fréquence (toujours, généralement, parfois, jamais)",
        "Ask how often the student does things — exercise, cook, watch a show, see friends."),
    MissionDay(7, "Ordre des mots dans les questions (est-ce que, inversion)",
        "Invite the student to interview you (Megan) back — get them to ask you questions about your life, city, hobbies."),
    MissionDay(8, "Combien de (dénombrable et indénombrable)",
        "Talk about shopping, prices, or quantities — how much something costs, how many people live in their city."),
    MissionDay(9, "Pouvoir (modal de capacité)",
        "Talk about skills and abilities — things the student can and can't do, like cook, swim, drive, play an instrument."),
    MissionDay(10, "Imparfait de \"être\"",
        "Ask where the student was yesterday, how their weekend was, how they were feeling this morning."),
    MissionDay(11, "Passé composé: verbes réguliers",
        "Ask what the student worked on, studied, or watched yesterday or last weekend."),
    MissionDay(12, "Passé composé: affirmatif, négatif, questions",
        "Dig into something specific that happened recently — ask follow-up questions and let them correct/deny things that aren't true."),
    MissionDay(13, "Passé composé: verbes irréguliers",
        "Ask about a trip, a meal, or an event — what they ate, went, saw, did, had recently."),
    MissionDay(14, "Il y a / il y avait (there is/are, there was/were)",
        "Ask the student to describe a place — their room, their city, or a party/event they went to."),
    MissionDay(15, "Pronoms compléments d'objet (me, te, le, la, nous, les)",
        "Talk about relationships and favors — asking someone for help, giving something to someone, telling someone news."),
    MissionDay(16, "Futur proche avec \"aller\" + infinitif (projets et prédictions)",
        "Ask about the student's plans for the weekend, next vacation, or predictions about something coming up."),
    MissionDay(17, "Comparatif (plus... que, moins... que, aussi... que)",
        "Compare two things the student knows well — two cities, two jobs, two friends, two phones."),
    MissionDay(18, "Superlatif (le/la plus..., le/la moins...)",
        "Ask about extremes in the student's life — the best trip, the worst job, the biggest city they've visited."),
    MissionDay(19, "Imparfait (verbes réguliers): habitudes et descriptions dans le passé",
        "Ask the student to describe what their life was like as a child — their house, their school, things they used to do."),
    MissionDay(20, "Imparfait vs passé composé: quand utiliser lequel",
        "Ask the student to tell a short story about something that happened while something else was going on (a specific event vs. the background situation)."),
    MissionDay(21, "Verbes modaux d'obligation et de conseil (devoir, il faut)",
        "Talk about rules and advice — things the student has to do at work or school, or should do to feel better."),
    MissionDay(22, "Conditionnel présent (type 1): si + présent, futur simple",
        "Ask about the student's plans depending on conditions — what they'll do if it rains, if they have free time, if they get a raise."),
    MissionDay(23, "Pronoms indéfinis (quelque chose, rien, quelqu'un, personne)",
        "Talk about what the student has or doesn't have right now — food at home, free time, plans for the weekend."),
    MissionDay(24, "Noms comptables et indénombrables (du, de la, des)",
        "Talk about food and shopping — how much or how many of different things the student needs or has."),
    MissionDay(25, "Prépositions de lieu (dans, sur, sous, à côté de)",
        "Ask the student to describe where things are around them — objects on their desk, furniture in their room."),
    MissionDay(26, "Prépositions de temps (à, en, pendant)",
        "Ask about the student's schedule — what they do in the morning, on weekends, or at a specific time."),
    MissionDay(27, "Verbe + infinitif (vouloir, devoir, aimer + infinitif)",
        "Ask what the student likes, wants, needs or has to do — hobbies, chores, plans."),
    MissionDay(28, "Pronoms réfléchis et verbes pronominaux (se réveiller, se sentir)",
        "Talk about routines the student does by themselves — getting ready, taking care of themselves, doing things alone."),
    MissionDay(29, "Pronoms relatifs (qui, que, où)",
        "Ask the student to describe people and things in their life with extra details — a friend who..., a job that..."),
    MissionDay(30, "Autrefois + imparfait (habitudes du passé, équivalent de \"used to\")",
        "Ask what the student used to do as a kid or years ago that they don't do anymore."),
)

private val francesModule2: List<MissionDay> = listOf(
    MissionDay(1, "Expressions avec \"avoir\" (en avoir marre, avoir hâte de, avoir du mal à)",
        "Ask what they're looking forward to, or something they're struggling with lately."),
    MissionDay(2, "Small talk (Comment ça va?, Quoi de neuf?, Ça fait longtemps!)",
        "Greet the student like you haven't talked in a while and catch up casually."),
    MissionDay(3, "Expressions avec \"se rendre\" (se rendre compte, se rendre à, se rendre utile)",
        "Talk about something they recently realized, or a time they made themselves useful."),
    MissionDay(4, "Donner son opinion (Je pense que, À mon avis, Pour être honnête)",
        "Ask the student's opinion about a movie, food, or something currently trending."),
    MissionDay(5, "Expressions avec \"s'occuper\" (s'occuper de, s'occuper à)",
        "Talk about who or what they take care of, or how they keep themselves busy."),
    MissionDay(6, "Être d'accord / pas d'accord (Je suis tout à fait d'accord, Je comprends mais...)",
        "Bring up a light opinion and get the student to agree or disagree with you."),
    MissionDay(7, "Expressions avec \"mettre\" (se mettre à, mettre au courant, remettre à plus tard)",
        "Talk about starting a new habit, keeping someone informed, or postponing something."),
    MissionDay(8, "Expressions sur le temps (juste à temps, prendre son temps, de temps en temps)",
        "Ask how often they do something, or about a time they almost arrived late."),
    MissionDay(9, "Expressions avec \"prendre\" (prendre soin de, s'y prendre, prendre sur soi)",
        "Talk about taking care of someone, how they approach a task, or staying calm under pressure."),
    MissionDay(10, "Faire des projets (Ça te dit de..., On pourrait..., Si on...)",
        "Plan a fake weekend activity together with the student."),
    MissionDay(11, "Expressions avec \"tomber\" (tomber sur, tomber d'accord, tomber malade)",
        "Talk about running into someone by chance, reaching an agreement, or getting sick recently."),
    MissionDay(12, "Réagir à une nouvelle (Pas possible!, C'est incroyable!, C'est dommage)",
        "Tell the student a piece of surprising made-up news and have them react."),
    MissionDay(13, "Expressions avec \"casser\" (casser les pieds, se casser la tête)",
        "Talk about something annoying, or a problem they racked their brain over."),
    MissionDay(14, "Expressions sur l'argent (coûter les yeux de la tête, mettre de l'argent de côté)",
        "Talk about a recent purchase or their saving habits."),
    MissionDay(15, "Expressions avec \"laisser\" (laisser tomber, laisser tranquille)",
        "Talk about giving up on something, or wanting to be left alone sometimes."),
    MissionDay(16, "Donner des conseils (Tu devrais..., Pourquoi tu ne..., À ta place...)",
        "Have the student describe a small problem and give them advice."),
    MissionDay(17, "Expressions avec \"courir\" (courir un risque, ça ne court pas les rues)",
        "Talk about a risk they took, or something rare and hard to find."),
    MissionDay(18, "Expressions sur les sentiments (être aux anges, avoir le cafard, en avoir ras le bol)",
        "Ask how they're feeling today using these expressions."),
    MissionDay(19, "Expressions avec \"aller\" (ça va aller, aller de soi)",
        "Talk about reassuring someone things will work out, or something that's obvious."),
    MissionDay(20, "Décrire les gens (avoir les pieds sur terre, sympa, plein d'énergie)",
        "Ask the student to describe a friend or family member."),
    MissionDay(21, "Expressions avec \"passer\" (passer un bon moment, passer outre)",
        "Talk about a good time they had recently, or ignoring a small problem."),
    MissionDay(22, "Expressions sur le travail et l'effort (retrousser ses manches, se donner à fond)",
        "Talk about a busy day at work or school."),
    MissionDay(23, "Expressions avec \"s'en sortir\" (s'en sortir, s'en sortir bien/mal)",
        "Talk about how they handled a difficult situation recently."),
    MissionDay(24, "Se plaindre poliment (Ça m'embête un peu que..., J'aimerais que...)",
        "Get the student to complain lightly about traffic, weather, or a busy week."),
    MissionDay(25, "Expressions avec \"sortir\" (sortir avec quelqu'un, s'en sortir)",
        "Talk about dating someone, or getting through a hard situation."),
    MissionDay(26, "Expressions sur la nourriture (du gâteau, vendre la mèche, faire bouillir la marmite)",
        "Use these while talking about an easy task, a secret, or supporting a family."),
    MissionDay(27, "Expressions avec \"régler\" (régler un problème, mettre les choses au clair)",
        "Talk about a problem they solved, or a misunderstanding they cleared up."),
    MissionDay(28, "S'excuser (C'était de ma faute, Je ne voulais pas, Ça n'arrivera plus)",
        "Set up a light scenario where the student apologizes for something small, like being late."),
    MissionDay(29, "Expressions avec \"rappeler\" (ça me rappelle, rappeler quelque chose à quelqu'un)",
        "Talk about something that reminds them of a memory, or a topic someone brought up."),
    MissionDay(30, "Expressions sur les relations (bien s'entendre avec, voir les choses de la même façon, briser la glace)",
        "Talk about getting along with coworkers or family, or agreeing with someone."),
)

val MissionFluencyFrenchCurriculum = LanguageCurriculum(
    listOf(
        "module1" to francesModule1,
        "module2" to francesModule2,
    )
)
