package schemas.alunoIa

/**
 * Currículo de alemão da Missão Fluência — mesma estrutura e progressão pedagógica do
 * [MissionFluencyCurriculum] (inglês), adaptada à gramática do alemão. Conteúdo gerado
 * como primeira versão: revisar com um falante nativo antes de publicar para alunos.
 */
private val alemaoModule1: List<MissionDay> = listOf(
    MissionDay(1, "Bestimmte und unbestimmte Artikel (der/die/das, ein/eine)",
        "Ask about the things on the student's desk, in their bag or around their room right now."),
    MissionDay(2, "Possessivartikel (mein, dein, sein, ihr...)",
        "Talk about family members — their jobs, their habits, their things ('das Auto meines Bruders', 'ihr Job')."),
    MissionDay(3, "Gerade + Präsens für Dinge, die jetzt gerade passieren",
        "Ask what's happening right now around the student, or what people in their house are doing at this moment."),
    MissionDay(4, "Präsens (regelmäßige und unregelmäßige Verben)",
        "Talk about the student's daily routine — what they usually do on a normal weekday."),
    MissionDay(5, "Die Uhrzeit",
        "Ask about the student's schedule today — what time they woke up, have lunch, or need to leave for something."),
    MissionDay(6, "Häufigkeitsadverbien (immer, normalerweise, manchmal, nie)",
        "Ask how often the student does things — exercise, cook, watch a show, see friends."),
    MissionDay(7, "Wortstellung in Fragen (W-Fragen und Ja/Nein-Fragen)",
        "Invite the student to interview you (Megan) back — get them to ask you questions about your life, city, hobbies."),
    MissionDay(8, "Wie viel und wie viele",
        "Talk about shopping, prices, or quantities — how much something costs, how many people live in their city."),
    MissionDay(9, "Können (Modalverb)",
        "Talk about skills and abilities — things the student can and can't do, like cook, swim, drive, play an instrument."),
    MissionDay(10, "Präteritum von \"sein\" (war, warst, waren)",
        "Ask where the student was yesterday, how their weekend was, how they were feeling this morning."),
    MissionDay(11, "Perfekt: regelmäßige Verben (haben/sein + Partizip II)",
        "Ask what the student worked on, studied, or watched yesterday or last weekend."),
    MissionDay(12, "Perfekt: bejaht, verneint, Fragen",
        "Dig into something specific that happened recently — ask follow-up questions and let them correct/deny things that aren't true."),
    MissionDay(13, "Perfekt: unregelmäßige Verben",
        "Ask about a trip, a meal, or an event — what they ate, went, saw, did, had recently."),
    MissionDay(14, "Es gibt / es gab (there is/are, there was/were)",
        "Ask the student to describe a place — their room, their city, or a party/event they went to."),
    MissionDay(15, "Akkusativpronomen (mich, dich, ihn, sie, uns, sie)",
        "Talk about relationships and favors — asking someone for help, giving something to someone, telling someone news."),
    MissionDay(16, "Futur mit \"werden\" (Pläne und Vorhersagen)",
        "Ask about the student's plans for the weekend, next vacation, or predictions about something coming up."),
    MissionDay(17, "Komparativ (Vergleiche mit \"als\" und \"wie\")",
        "Compare two things the student knows well — two cities, two jobs, two friends, two phones."),
    MissionDay(18, "Superlativ (am + Adjektiv + -sten)",
        "Ask about extremes in the student's life — the best trip, the worst job, the biggest city they've visited."),
    MissionDay(19, "Nebensätze mit \"weil\" (Kausalsätze, Verb am Ende)",
        "Ask the student WHY they do things — why they chose their job, why they like their city, why they're learning German."),
    MissionDay(20, "Nebensätze mit \"dass\" (Objektsätze)",
        "Ask the student what they think or believe about something — their opinion on a topic, or something they've heard or read recently."),
    MissionDay(21, "Modalverben für Pflicht und Rat (müssen, sollen)",
        "Talk about rules and advice — things the student has to do at work or school, or should do to feel better."),
    MissionDay(22, "Wenn-Sätze Typ 1 (wenn + Präsens, werden + Infinitiv)",
        "Ask about the student's plans depending on conditions — what they'll do if it rains, if they have free time, if they get a raise."),
    MissionDay(23, "Indefinitpronomen (etwas, nichts, jemand, niemand)",
        "Talk about what the student has or doesn't have right now — food at home, free time, plans for the weekend."),
    MissionDay(24, "Zählbare und unzählbare Nomen (mit Mengenangaben)",
        "Talk about food and shopping — how much or how many of different things the student needs or has."),
    MissionDay(25, "Präpositionen des Ortes (in, auf, unter, neben)",
        "Ask the student to describe where things are around them — objects on their desk, furniture in their room."),
    MissionDay(26, "Präpositionen der Zeit (um, am, im)",
        "Ask about the student's schedule — what they do in the morning, on weekends, or at a specific time."),
    MissionDay(27, "\"Zu\" + Infinitiv nach Ausdrücken wie \"Lust haben\", \"vorhaben\", \"versuchen\"",
        "Ask what the student likes, wants, needs or has to do — hobbies, chores, plans."),
    MissionDay(28, "Reflexivpronomen und reflexive Verben (sich freuen, sich fühlen)",
        "Talk about routines the student does by themselves — getting ready, taking care of themselves, doing things alone."),
    MissionDay(29, "Relativsätze (der, die, das als Relativpronomen)",
        "Ask the student to describe people and things in their life with extra details — a friend who..., a job that..."),
    MissionDay(30, "Früher + Perfekt (Gewohnheiten in der Vergangenheit)",
        "Ask what the student used to do as a kid or years ago that they don't do anymore."),
)

private val alemaoModule2: List<MissionDay> = listOf(
    MissionDay(1, "Trennbare Verben mit \"auf\" (aufstehen, aufhören, aufpassen)",
        "Ask about the student's morning routine, or something they need to pay attention to."),
    MissionDay(2, "Small Talk (Wie geht's?, Was gibt's Neues?, Lange nicht gesehen)",
        "Greet the student like you haven't talked in a while and catch up casually."),
    MissionDay(3, "Trennbare Verben mit \"an\" (ankommen, anfangen, sich etwas anschauen)",
        "Talk about arriving somewhere, or starting a new project or habit."),
    MissionDay(4, "Meinungen äußern (Ich finde, Meiner Meinung nach, Ehrlich gesagt)",
        "Ask the student's opinion about a movie, food, or something currently trending."),
    MissionDay(5, "Trennbare Verben mit \"aus\" (ausgehen, ausschlafen, ausprobieren)",
        "Talk about going out, sleeping in, or trying something new."),
    MissionDay(6, "Zustimmen und widersprechen (Ich stimme total zu, Ich verstehe deinen Punkt, aber...)",
        "Bring up a light opinion and get the student to agree or disagree with you."),
    MissionDay(7, "Trennbare Verben mit \"ein\" (einkaufen, einschlafen, sich einleben)",
        "Talk about grocery shopping, falling asleep, or settling into a new place."),
    MissionDay(8, "Redewendungen über Zeit (auf den letzten Drücker, sich Zeit lassen, alle Jubeljahre)",
        "Ask how often they do something, or about a time they almost arrived late."),
    MissionDay(9, "Trennbare Verben mit \"mit\" (mitmachen, mitkommen, mitbringen)",
        "Talk about joining an activity, or something they'll bring to an event."),
    MissionDay(10, "Pläne machen (Wie wäre es mit..., Hast du Lust..., Lass uns...)",
        "Plan a fake weekend activity together with the student."),
    MissionDay(11, "Trennbare Verben mit \"vor\" (vorschlagen, sich vorstellen, vorbereiten)",
        "Talk about proposing an idea, or preparing for something coming up."),
    MissionDay(12, "Auf Neuigkeiten reagieren (Das gibt's doch nicht!, Das ist ja toll!, Wie schade)",
        "Tell the student a piece of surprising made-up news and have them react."),
    MissionDay(13, "Trennbare Verben mit \"ab\" (abbrechen, abnehmen, sich abmelden)",
        "Talk about cancelling plans, losing weight, or logging off from something."),
    MissionDay(14, "Redewendungen übers Geld (ein Vermögen kosten, für schlechte Zeiten sparen)",
        "Talk about a recent purchase or their saving habits."),
    MissionDay(15, "Trennbare Verben mit \"weg\" (weggehen, wegwerfen, weglaufen)",
        "Talk about going out, throwing something away, or running from a problem."),
    MissionDay(16, "Ratschläge geben (Du solltest..., Warum machst du nicht..., An deiner Stelle...)",
        "Have the student describe a small problem and give them advice."),
    MissionDay(17, "Trennbare Verben mit \"um\" (umziehen, sich umsehen, umtauschen)",
        "Talk about moving house, looking around a new place, or exchanging something."),
    MissionDay(18, "Redewendungen über Gefühle (auf Wolke sieben, niedergeschlagen sein, die Nase voll haben)",
        "Ask how they're feeling today using these expressions."),
    MissionDay(19, "Trennbare Verben mit \"los\" (losfahren, loslassen, loslegen)",
        "Talk about setting off somewhere, letting go of something, or getting started on a task."),
    MissionDay(20, "Menschen beschreiben (bodenständig, locker, voller Energie)",
        "Ask the student to describe a friend or family member."),
    MissionDay(21, "Trennbare Verben mit \"zu\" (zuhören, zunehmen, zusehen)",
        "Talk about listening to someone, gaining something, or watching an event happen."),
    MissionDay(22, "Redewendungen über Arbeit und Mühe (die Ärmel hochkrempeln, voll durchstarten)",
        "Talk about a busy day at work or school."),
    MissionDay(23, "Trennbare Verben mit \"durch\" (durcharbeiten, durchhalten, sich durchsetzen)",
        "Talk about working through something, pushing through a hard week, or standing your ground."),
    MissionDay(24, "Höflich beschweren (Es stört mich ein bisschen, dass..., Ich wünschte...)",
        "Get the student to complain lightly about traffic, weather, or a busy week."),
    MissionDay(25, "Trennbare Verben mit \"fest\" (feststehen, festhalten, sich festlegen)",
        "Talk about something that's already decided, holding onto something, or committing to a plan."),
    MissionDay(26, "Redewendungen übers Essen (ein Kinderspiel, etwas ausplaudern, den Lebensunterhalt verdienen)",
        "Use these while talking about an easy task, a secret, or supporting a family."),
    MissionDay(27, "Trennbare Verben mit \"heraus\" (herausfinden, herauskommen)",
        "Talk about finding something out, or something that came out recently (news, a product)."),
    MissionDay(28, "Sich entschuldigen (Das war meine Schuld, Das war nicht meine Absicht, Es wird nicht wieder vorkommen)",
        "Set up a light scenario where the student apologizes for something small, like being late."),
    MissionDay(29, "Trennbare Verben mit \"zurück\" (zurückkommen, zurückbringen, zurückrufen)",
        "Talk about coming back from a trip, giving something back, or calling someone back."),
    MissionDay(30, "Redewendungen über Beziehungen (gut auskommen mit, einer Meinung sein, das Eis brechen)",
        "Talk about getting along with coworkers or family, or agreeing with someone."),
)

val MissionFluencyGermanCurriculum = LanguageCurriculum(
    listOf(
        "module1" to alemaoModule1,
        "module2" to alemaoModule2,
    )
)
