package schemas.alunoIa

/**
 * Currículo de espanhol da Missão Fluência — mesma estrutura e progressão pedagógica do
 * [MissionFluencyCurriculum] (inglês), adaptada à gramática do espanhol. Conteúdo gerado
 * como primeira versão: revisar com um falante nativo antes de publicar para alunos.
 */
private val espanholModule1: List<MissionDay> = listOf(
    MissionDay(1, "Artículos definidos e indefinidos (el/la/los/las, un/una/unos/unas)",
        "Ask about the things on the student's desk, in their bag or around their room right now."),
    MissionDay(2, "Adjetivos posesivos (mi, tu, su, nuestro...)",
        "Talk about family members — their jobs, their habits, their things ('el coche de mi hermano', 'su trabajo')."),
    MissionDay(3, "Presente continuo (estar + gerundio)",
        "Ask what's happening right now around the student, or what people in their house are doing at this moment."),
    MissionDay(4, "Presente simple (verbos regulares e irregulares comunes)",
        "Talk about the student's daily routine — what they usually do on a normal weekday."),
    MissionDay(5, "Decir la hora",
        "Ask about the student's schedule today — what time they woke up, have lunch, or need to leave for something."),
    MissionDay(6, "Adverbios de frecuencia (siempre, normalmente, a veces, nunca)",
        "Ask how often the student does things — exercise, cook, watch a show, see friends."),
    MissionDay(7, "Orden de las palabras en preguntas",
        "Invite the student to interview you (Megan) back — get them to ask you questions about your life, city, hobbies."),
    MissionDay(8, "Cuánto y cuántos/cuántas",
        "Talk about shopping, prices, or quantities — how much something costs, how many people live in their city."),
    MissionDay(9, "Poder (modal de habilidad)",
        "Talk about skills and abilities — things the student can and can't do, like cook, swim, drive, play an instrument."),
    MissionDay(10, "Pretérito de \"ser\" y \"estar\"",
        "Ask where the student was yesterday, how their weekend was, how they were feeling this morning."),
    MissionDay(11, "Pretérito indefinido: verbos regulares",
        "Ask what the student worked on, studied, or watched yesterday or last weekend."),
    MissionDay(12, "Pretérito indefinido: afirmativo, negativo, preguntas",
        "Dig into something specific that happened recently — ask follow-up questions and let them correct/deny things that aren't true."),
    MissionDay(13, "Pretérito indefinido: verbos irregulares",
        "Ask about a trip, a meal, or an event — what they ate, went, saw, did, had recently."),
    MissionDay(14, "Hay / había (there is/are, there was/were)",
        "Ask the student to describe a place — their room, their city, or a party/event they went to."),
    MissionDay(15, "Pronombres de objeto (me, te, lo, la, nos, los, las)",
        "Talk about relationships and favors — asking someone for help, giving something to someone, telling someone news."),
    MissionDay(16, "Futuro con \"ir a\" + infinitivo (planes y predicciones)",
        "Ask about the student's plans for the weekend, next vacation, or predictions about something coming up."),
    MissionDay(17, "Comparativos (más...que, menos...que, tan...como)",
        "Compare two things the student knows well — two cities, two jobs, two friends, two phones."),
    MissionDay(18, "Superlativos (el/la más..., el/la menos...)",
        "Ask about extremes in the student's life — the best trip, the worst job, the biggest city they've visited."),
    MissionDay(19, "Pretérito imperfecto (hábitos y descripciones en el pasado)",
        "Ask the student to describe what their life was like as a child — their house, their school, things they used to do."),
    MissionDay(20, "Imperfecto vs. indefinido: cuándo usar cada uno",
        "Ask the student to tell a short story about something that happened while something else was going on (a specific event vs. the background situation)."),
    MissionDay(21, "Verbos modales de obligación y consejo (tener que, deber)",
        "Talk about rules and advice — things the student has to do at work or school, or should do to feel better."),
    MissionDay(22, "Condicional tipo 1 (si + presente, futuro)",
        "Ask about the student's plans depending on conditions — what they'll do if it rains, if they have free time, if they get a raise."),
    MissionDay(23, "Pronombres indefinidos (algo, nada, alguien, nadie)",
        "Talk about what the student has or doesn't have right now — food at home, free time, plans for the weekend."),
    MissionDay(24, "Sustantivos contables e incontables",
        "Talk about food and shopping — how much or how many of different things the student needs or has."),
    MissionDay(25, "Preposiciones de lugar (en, sobre, debajo de, al lado de)",
        "Ask the student to describe where things are around them — objects on their desk, furniture in their room."),
    MissionDay(26, "Preposiciones de tiempo (a, en, por)",
        "Ask about the student's schedule — what they do in the morning, on weekends, or at a specific time."),
    MissionDay(27, "Verbo + infinitivo (querer, tener que, gustar + infinitivo)",
        "Ask what the student likes, wants, needs or has to do — hobbies, chores, plans."),
    MissionDay(28, "Pronombres reflexivos y verbos reflexivos (levantarse, sentirse)",
        "Talk about routines the student does by themselves — getting ready, taking care of themselves, doing things alone."),
    MissionDay(29, "Pronombres relativos (que, quien, donde)",
        "Ask the student to describe people and things in their life with extra details — a friend who..., a job that..."),
    MissionDay(30, "Antes + imperfecto (hábitos en el pasado, equivalente a \"used to\")",
        "Ask what the student used to do as a kid or years ago that they don't do anymore."),
)

private val espanholModule2: List<MissionDay> = listOf(
    MissionDay(1, "Expresiones con \"quedar\" (quedar con alguien, quedar bien/mal, quedar en algo)",
        "Ask about meeting up with friends, and whether plans they made actually happened."),
    MissionDay(2, "Small talk (¿Qué tal?, ¿Cómo te va?, Cuánto tiempo sin verte)",
        "Greet the student like you haven't talked in a while and catch up casually."),
    MissionDay(3, "Expresiones con \"echar\" (echar de menos, echarle ganas, echar una mano)",
        "Ask who or what they miss, or about a time they helped someone out."),
    MissionDay(4, "Dar opiniones (Creo que, En mi opinión, La verdad es que)",
        "Ask the student's opinion about a movie, food, or something currently trending."),
    MissionDay(5, "Expresiones con \"ponerse\" (ponerse a + infinitivo, ponerse nervioso/a, ponerse de acuerdo)",
        "Talk about starting a new habit, or getting nervous before something."),
    MissionDay(6, "Estar de acuerdo / en desacuerdo (Estoy totalmente de acuerdo, Entiendo tu punto pero...)",
        "Bring up a light opinion and get the student to agree or disagree with you."),
    MissionDay(7, "Expresiones con \"dar\" (dar igual, darse cuenta, dar la lata)",
        "Talk about something they recently realized, or something that doesn't matter to them."),
    MissionDay(8, "Modismos sobre el tiempo (justo a tiempo, tómate tu tiempo, de vez en cuando)",
        "Ask how often they do something, or about a time they almost arrived late."),
    MissionDay(9, "Expresiones con \"llevar\" (llevarse bien/mal, llevar tiempo haciendo algo)",
        "Talk about how well they get along with someone, or how long they've been doing something."),
    MissionDay(10, "Hacer planes (¿Qué tal si..., Te apetece..., Vamos a...)",
        "Plan a fake weekend activity together with the student."),
    MissionDay(11, "Expresiones con \"meter(se)\" (meterse en problemas, meter la pata)",
        "Talk about a time they made a mistake, or almost got into trouble."),
    MissionDay(12, "Reaccionar a noticias (¡No puede ser!, ¡Qué increíble!, Qué pena)",
        "Tell the student a piece of surprising made-up news and have them react."),
    MissionDay(13, "Expresiones con \"romper\" (romper con alguien, romper a llorar/reír)",
        "Talk about a breakup, or a moment someone suddenly burst out laughing or crying."),
    MissionDay(14, "Modismos sobre el dinero (costar un ojo de la cara, ahorrar para un día lluvioso)",
        "Talk about a recent purchase or their saving habits."),
    MissionDay(15, "Expresiones con \"dejar\" (dejar de + infinitivo, dejar plantado a alguien)",
        "Talk about a habit they quit, or a time someone stood them up."),
    MissionDay(16, "Dar consejos (Deberías..., ¿Por qué no..., Yo que tú...)",
        "Have the student describe a small problem and give them advice."),
    MissionDay(17, "Expresiones con \"correr\" (correr prisa, correr un riesgo)",
        "Talk about something urgent, or a risk they took recently."),
    MissionDay(18, "Modismos sobre sentimientos (estar en las nubes, estar de bajón, estar hasta las narices)",
        "Ask how they're feeling today using these expressions."),
    MissionDay(19, "Expresiones con \"ir\" (irle bien/mal a alguien, ir sobre ruedas)",
        "Talk about how something is going for them, or a plan that's going smoothly."),
    MissionDay(20, "Describir personas (con los pies en la tierra, buena onda, lleno de energía)",
        "Ask the student to describe a friend or family member."),
    MissionDay(21, "Expresiones con \"pasar\" (pasarlo bien/mal, pasar de algo)",
        "Talk about a good or bad time they had recently, or something they'd rather ignore."),
    MissionDay(22, "Modismos sobre trabajo y esfuerzo (dar el callo, echarle muchas horas)",
        "Talk about a busy day at work or school."),
    MissionDay(23, "Expresiones con \"funcionar\" (funcionar bien/mal, funcionar a la perfección)",
        "Talk about something that worked well or broke down recently."),
    MissionDay(24, "Quejarse con educación (Me molesta un poco que..., Ojalá...)",
        "Get the student to complain lightly about traffic, weather, or a busy week."),
    MissionDay(25, "Expresiones con \"salir\" (salir con alguien, salir adelante)",
        "Talk about dating someone, or getting through a hard situation."),
    MissionDay(26, "Modismos sobre comida (pan comido, irse de la lengua, ser el sostén de la familia)",
        "Use these while talking about an easy task, a secret, or supporting a family."),
    MissionDay(27, "Expresiones con \"resolver\" y \"aclarar\" (resolver un problema, aclarar las cosas)",
        "Talk about a problem they solved or cleared up recently."),
    MissionDay(28, "Disculparse (Fue mi culpa, No fue mi intención, No volverá a pasar)",
        "Set up a light scenario where the student apologizes for something small, like being late."),
    MissionDay(29, "Expresiones con \"traer\" (traer recuerdos, traer algo a colación)",
        "Talk about something that brought back memories, or a topic someone brought up."),
    MissionDay(30, "Modismos sobre relaciones (llevarse bien con alguien, ver las cosas igual, romper el hielo)",
        "Talk about getting along with coworkers or family, or agreeing with someone."),
)

val MissionFluencySpanishCurriculum = LanguageCurriculum(
    listOf(
        "module1" to espanholModule1,
        "module2" to espanholModule2,
    )
)
