package schemas.alunoIa

/**
 * Currículo de holandês da Missão Fluência — mesma estrutura e progressão pedagógica do
 * [MissionFluencyCurriculum] (inglês), adaptada à gramática do holandês. Conteúdo gerado
 * como primeira versão: revisar com um falante nativo antes de publicar para alunos.
 */
private val holandesModule1: List<MissionDay> = listOf(
    MissionDay(1, "Bepaald en onbepaald lidwoord (de/het, een)",
        "Ask about the things on the student's desk, in their bag or around their room right now."),
    MissionDay(2, "Bezittelijke voornaamwoorden (mijn, jouw, zijn, haar, ons...)",
        "Talk about family members — their jobs, their habits, their things ('de auto van mijn broer', 'haar baan')."),
    MissionDay(3, "Tegenwoordige tijd voor dingen die nu gebeuren (\"aan het\" + infinitief)",
        "Ask what's happening right now around the student, or what people in their house are doing at this moment."),
    MissionDay(4, "Tegenwoordige tijd (regelmatige en onregelmatige werkwoorden)",
        "Talk about the student's daily routine — what they usually do on a normal weekday."),
    MissionDay(5, "De tijd zeggen",
        "Ask about the student's schedule today — what time they woke up, have lunch, or need to leave for something."),
    MissionDay(6, "Bijwoorden van frequentie (altijd, meestal, soms, nooit)",
        "Ask how often the student does things — exercise, cook, watch a show, see friends."),
    MissionDay(7, "Woordvolgorde in vragen",
        "Invite the student to interview you (Megan) back — get them to ask you questions about your life, city, hobbies."),
    MissionDay(8, "Hoeveel (telbaar en ontelbaar)",
        "Talk about shopping, prices, or quantities — how much something costs, how many people live in their city."),
    MissionDay(9, "Kunnen (modaal werkwoord)",
        "Talk about skills and abilities — things the student can and can't do, like cook, swim, drive, play an instrument."),
    MissionDay(10, "Verleden tijd van \"zijn\" (was, waren)",
        "Ask where the student was yesterday, how their weekend was, how they were feeling this morning."),
    MissionDay(11, "Voltooid tegenwoordige tijd: regelmatige werkwoorden",
        "Ask what the student worked on, studied, or watched yesterday or last weekend."),
    MissionDay(12, "Voltooid tegenwoordige tijd: bevestigend, ontkennend, vragen",
        "Dig into something specific that happened recently — ask follow-up questions and let them correct/deny things that aren't true."),
    MissionDay(13, "Voltooid tegenwoordige tijd: onregelmatige werkwoorden",
        "Ask about a trip, a meal, or an event — what they ate, went, saw, did, had recently."),
    MissionDay(14, "Er is/zijn, er was/waren (there is/are, there was/were)",
        "Ask the student to describe a place — their room, their city, or a party/event they went to."),
    MissionDay(15, "Objectvoornaamwoorden (mij, jou, hem, haar, ons, hen)",
        "Talk about relationships and favors — asking someone for help, giving something to someone, telling someone news."),
    MissionDay(16, "Toekomende tijd met \"gaan\" + infinitief (plannen en voorspellingen)",
        "Ask about the student's plans for the weekend, next vacation, or predictions about something coming up."),
    MissionDay(17, "Vergrotende trap (comparatief: -er, meer...)",
        "Compare two things the student knows well — two cities, two jobs, two friends, two phones."),
    MissionDay(18, "Overtreffende trap (superlatief: -st, meest...)",
        "Ask about extremes in the student's life — the best trip, the worst job, the biggest city they've visited."),
    MissionDay(19, "Bijzinnen met \"omdat\" (reden geven, werkwoord op het einde)",
        "Ask the student WHY they do things — why they chose their job, why they like their city, why they're learning Dutch."),
    MissionDay(20, "Bijzinnen met \"dat\" (objectzinnen)",
        "Ask the student what they think or believe about something — their opinion on a topic, or something they've heard or read recently."),
    MissionDay(21, "Modale werkwoorden voor verplichting en advies (moeten, zou moeten)",
        "Talk about rules and advice — things the student has to do at work or school, or should do to feel better."),
    MissionDay(22, "Voorwaardelijke zinnen type 1 (als + tegenwoordige tijd, gaan/zullen + infinitief)",
        "Ask about the student's plans depending on conditions — what they'll do if it rains, if they have free time, if they get a raise."),
    MissionDay(23, "Onbepaalde voornaamwoorden (iets, niets, iemand, niemand)",
        "Talk about what the student has or doesn't have right now — food at home, free time, plans for the weekend."),
    MissionDay(24, "Telbare en ontelbare zelfstandige naamwoorden",
        "Talk about food and shopping — how much or how many of different things the student needs or has."),
    MissionDay(25, "Voorzetsels van plaats (in, op, onder, naast)",
        "Ask the student to describe where things are around them — objects on their desk, furniture in their room."),
    MissionDay(26, "Voorzetsels van tijd (om, op, in)",
        "Ask about the student's schedule — what they do in the morning, on weekends, or at a specific time."),
    MissionDay(27, "Werkwoord + \"te\" + infinitief (proberen te, van plan zijn te)",
        "Ask what the student likes, wants, needs or has to do — hobbies, chores, plans."),
    MissionDay(28, "Wederkerende voornaamwoorden en werkwoorden (zich voelen, zich herinneren)",
        "Talk about routines the student does by themselves — getting ready, taking care of themselves, doing things alone."),
    MissionDay(29, "Betrekkelijke bijzinnen (die, dat als betrekkelijk voornaamwoord)",
        "Ask the student to describe people and things in their life with extra details — a friend who..., a job that..."),
    MissionDay(30, "Vroeger + verleden tijd (gewoontes in het verleden)",
        "Ask what the student used to do as a kid or years ago that they don't do anymore."),
)

private val holandesModule2: List<MissionDay> = listOf(
    MissionDay(1, "Scheidbare werkwoorden met \"op\" (opstaan, ophouden, opletten)",
        "Ask about the student's morning routine, or something they need to pay attention to."),
    MissionDay(2, "Small talk (Hoe gaat het?, Wat is er nieuw?, Lang niet gezien)",
        "Greet the student like you haven't talked in a while and catch up casually."),
    MissionDay(3, "Scheidbare werkwoorden met \"aan\" (aankomen, aanpakken, iets aandurven)",
        "Talk about arriving somewhere, tackling a problem, or daring to try something new."),
    MissionDay(4, "Meningen geven (Ik denk dat, Volgens mij, Eerlijk gezegd)",
        "Ask the student's opinion about a movie, food, or something currently trending."),
    MissionDay(5, "Scheidbare werkwoorden met \"uit\" (uitgaan, uitslapen, uitproberen)",
        "Talk about going out, sleeping in, or trying something new."),
    MissionDay(6, "Het eens/oneens zijn (Ik ben het er helemaal mee eens, Ik snap je punt, maar...)",
        "Bring up a light opinion and get the student to agree or disagree with you."),
    MissionDay(7, "Scheidbare werkwoorden met \"in\" (inpakken, in slaap vallen, zich inleven)",
        "Talk about packing for a trip, falling asleep, or settling into a new place."),
    MissionDay(8, "Uitdrukkingen over tijd (op het nippertje, de tijd nemen, af en toe)",
        "Ask how often they do something, or about a time they almost arrived late."),
    MissionDay(9, "Scheidbare werkwoorden met \"mee\" (meedoen, meekomen, meebrengen)",
        "Talk about joining an activity, or something they'll bring to an event."),
    MissionDay(10, "Plannen maken (Wat dacht je van..., Heb je zin om..., Laten we...)",
        "Plan a fake weekend activity together with the student."),
    MissionDay(11, "Scheidbare werkwoorden met \"voor\" (voorstellen, zich voorbereiden)",
        "Talk about proposing an idea, or preparing for something coming up."),
    MissionDay(12, "Reageren op nieuws (Dat meen je niet!, Wat geweldig!, Wat jammer)",
        "Tell the student a piece of surprising made-up news and have them react."),
    MissionDay(13, "Scheidbare werkwoorden met \"af\" (afmaken, afvallen, zich afmelden)",
        "Talk about finishing a task, losing weight, or logging off from something."),
    MissionDay(14, "Uitdrukkingen over geld (een fortuin kosten, sparen voor een regenachtige dag)",
        "Talk about a recent purchase or their saving habits."),
    MissionDay(15, "Scheidbare werkwoorden met \"weg\" (weggaan, weggooien, weglopen)",
        "Talk about leaving somewhere, throwing something away, or running from a problem."),
    MissionDay(16, "Advies geven (Je zou moeten..., Waarom doe je niet..., Als ik jou was...)",
        "Have the student describe a small problem and give them advice."),
    MissionDay(17, "Scheidbare werkwoorden met \"om\" (omkijken, omruilen, omdraaien)",
        "Talk about looking back on something, exchanging an item, or turning a situation around."),
    MissionDay(18, "Uitdrukkingen over gevoelens (in de wolken zijn, zich down voelen, het helemaal gehad hebben)",
        "Ask how they're feeling today using these expressions."),
    MissionDay(19, "Scheidbare werkwoorden met \"los\" (loslaten, losgaan, loskomen)",
        "Talk about letting go of something, or finally getting comfortable in a situation."),
    MissionDay(20, "Mensen beschrijven (nuchter, relaxed, vol energie)",
        "Ask the student to describe a friend or family member."),
    MissionDay(21, "Scheidbare werkwoorden met \"toe\" (toekijken, toenemen, toegeven)",
        "Talk about watching something happen, something increasing, or admitting a mistake."),
    MissionDay(22, "Uitdrukkingen over werk en inzet (de handen uit de mouwen steken, ergens vol voor gaan)",
        "Talk about a busy day at work or school."),
    MissionDay(23, "Scheidbare werkwoorden met \"door\" (doorwerken, doorzetten, doorgaan)",
        "Talk about working through something, pushing through a hard week, or continuing a plan."),
    MissionDay(24, "Beleefd klagen (Het stoort me een beetje dat..., Ik wou dat...)",
        "Get the student to complain lightly about traffic, weather, or a busy week."),
    MissionDay(25, "Scheidbare werkwoorden met \"vast\" (vaststaan, vasthouden, zich vastleggen)",
        "Talk about something already decided, holding onto something, or committing to a plan."),
    MissionDay(26, "Uitdrukkingen over eten (een makkie, uit de school klappen, de kost verdienen)",
        "Use these while talking about an easy task, a secret, or supporting a family."),
    MissionDay(27, "Scheidbare werkwoorden met \"terug\" (terugkomen, teruggeven, terugbellen)",
        "Talk about coming back from a trip, giving something back, or calling someone back."),
    MissionDay(28, "Excuses maken (Het was mijn schuld, Ik bedoelde het niet zo, Het zal niet meer gebeuren)",
        "Set up a light scenario where the student apologizes for something small, like being late."),
    MissionDay(29, "Uitdrukkingen met \"brengen\" (iets in herinnering brengen, iets ter sprake brengen)",
        "Talk about something that brought back memories, or a topic someone brought up."),
    MissionDay(30, "Uitdrukkingen over relaties (goed opschieten met, het ergens over eens zijn, het ijs breken)",
        "Talk about getting along with coworkers or family, or agreeing with someone."),
)

val MissionFluencyDutchCurriculum = LanguageCurriculum(
    listOf(
        "module1" to holandesModule1,
        "module2" to holandesModule2,
    )
)
